Repository sufst/can-defs, pull requests merged in 2023-02, with the labels that each got.

#5 release: v0.0.1
  .gitignore
  README.md
  out/can_database.c
  out/can_database.h
  out/can_handlers.c
  out/can_handlers.h
  out/schema.json
  out/sensors.json
Labels: documentation, feature

#6 feat: initial DBC for CAN-C bus
  README.md
  dbc/CAN-C.dbc
  dbc/PM100DZ_Gen5.dbc
  dbc/manufacturer/20210505 RMS PM and RM CAN DB.dbc
Labels: documentation, feature

#7 release: v0.0.2
  out/can_database.c
  out/can_database.h
  out/can_handlers.c
  out/schema.json
  out/sensors.json
Labels: feature

#9 fix: include `stddef.h` in generated C code
  out/can_handlers.h
Labels: bug

#10 release: v0.0.3
  out/can_database.c
  out/can_database.h
  out/can_handlers.h
Labels: feature

#11 fix: add `stddef.h` to C code generation
  tsgen/__main__.py
Labels: bug, feature

#12 release: v0.0.4
  out/can_database.c
  out/can_database.h
  out/can_handlers.h
Labels: feature

#14 feat: sort PDUs by CAN message priority
  tsgen/__main__.py
Labels: feature
